#列表
my_list=[555,2,777,4,44,6,7,8,9]
print(my_list[3])
my_list[4]=888
my_list.append(444)
print(my_list)
right=my_list.pop()
print(right)
print(my_list)
my_list.sort()
print(my_list)
my_list.reverse()
print(my_list)

'''字典'''
my_dict={"大撒":"100","大漂梁":"70","大聪明":"60"}
print(my_dict)
my_dict["大撒"]="hhh"
keys=my_dict.keys()
print(keys)
values=my_dict.values()
print(values)
items=my_dict.items()
print(items)
print(my_dict.get("大聪明","略略略"))
my_dict.update({"大撒":"hhhhhh"})
print(my_dict)
shanshanshan=my_dict.pop("大聪明")
print(shanshanshan)
print(my_dict)
'''元组'''
tuple1=('气死我了','1884','小爷超无语的','想做个健康的ren','我是个man')
tuplefu=('气死我了','1884','wuyu','健康个鬼','我是个man')
print(tuple1)
print(tuple1[0])
print(tuplefu[1:3])
print(tuplefu[:3])
print(tuplefu*2)
print(tuple1+tuplefu)
print(tuple1.index("我是个man"))
print(tuplefu.count("1884"))

'''集合'''
set1={4,9,41,12,45,10,11}
set2={4,77,41,1,45,0,11}
print(set1&set2)
print(set1-set2)
print(set1|set2)